# Generated by Django 3.2.8 on 2021-10-15 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0004_auto_20211013_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[a-zA-Z]$')]),
        ),
    ]
